# Repository settings to disable email notifications
repository:
  # Disable email notifications for workflow runs
  has_issues: true
  has_projects: true
  has_wiki: false
  
  # Default settings for pull requests and issues
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  
  # Security settings
  vulnerability_alerts: false
  security_and_analysis:
    secret_scanning:
      status: disabled
    secret_scanning_push_protection:
      status: disabled

# Disable email notifications for Actions
notifications:
  emails: []
  webhooks: [] 