apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-rag-backend
  labels:
    app: enterprise-rag-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enterprise-rag-backend
  template:
    metadata:
      labels:
        app: enterprise-rag-backend
    spec:
      containers:
      - name: backend
        image: enterprise-rag-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PROVIDER
          value: "openai"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-rag-ui
  labels:
    app: enterprise-rag-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-rag-ui
  template:
    metadata:
      labels:
        app: enterprise-rag-ui
    spec:
      containers:
      - name: ui
        image: enterprise-rag-ui:latest
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_URL
          value: "http://enterprise-rag-backend-service:8000"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
