apiVersion: v1
kind: Service
metadata:
  name: enterprise-rag-backend-service
  labels:
    app: enterprise-rag-backend
spec:
  selector:
    app: enterprise-rag-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-rag-ui-service
  labels:
    app: enterprise-rag-ui
spec:
  selector:
    app: enterprise-rag-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
type: Opaque
stringData:
  openai-api-key: "your-openai-api-key-here"
  anthropic-api-key: "your-anthropic-api-key-here"
  google-api-key: "your-google-api-key-here"
