version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./tmp:/app/tmp
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app
    environment:
      - BACKEND_URL=http://backend:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_PROVIDER=${MODEL_PROVIDER:-openai}
    depends_on:
      - backend
    command: python main.py

volumes:
  tmp_data:
