name: Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Disable email notifications
env:
  ACTIONS_RUNNER_DEBUG: false
  ACTIONS_STEP_DEBUG: false

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    continue-on-error: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r backend/requirements.txt
        pip install -r tests/requirements.txt
    
    - name: Basic syntax check
      run: |
        # Check for syntax errors and undefined names only
        flake8 backend/app --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Run tests
      run: |
        cd backend
        python -m pytest ../tests/backend/ -v --maxfail=5 --tb=short
      env:
        OPENAI_API_KEY: "test-key-for-ci" 